ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"  
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]
[traps.deployment_monitor]
path = "out/Trap.sol/Trap.json"
response_contract = "0xdA1F9C9AD19299CaD0F0D479D2908434c9FfC3C1"
response_function = "handleDeploymentAlert(string,uint256,uint256,uint256,bool,bool,bool,string)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private = true
private_trap = true
whitelist = [
    "YourWalletAddress"
]
